version: 2
jobs:
  build:
    docker:
      - image: salsify/ruby_ci:2.5.1
    working_directory: ~/gtin
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-2.5.1-{{ checksum "gtin.gemspec" }}-{{ checksum "Gemfile.lock" }}
            - v1-gems-ruby-2.5.1-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-2.5.1-{{ checksum "gtin.gemspec" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
            - "gemfiles/vendor"
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/junit.xml --format progress spec
      - store_test_results:
          path: 'test-results'
